# Generated by Django 3.2.8 on 2021-12-15 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_confirmstring_user'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='日记标题')),
                ('content', models.TextField(verbose_name='日记内容')),
                ('square_open', models.BooleanField(default=False, verbose_name='是否公开')),
                ('expire_time', models.DateTimeField(null=True, verbose_name='解封日期')),
                ('status', models.BooleanField(default=False, verbose_name='是否到期')),
                ('diary_type', models.CharField(choices=[('pill', '胶囊日记'), ('primary', '普通日记')], default='胶囊日记', max_length=8, verbose_name='日记类型')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.user', verbose_name='作者ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.article', verbose_name='评论文章')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.user', verbose_name='评论者')),
                ('pre_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.comment', verbose_name='父评论id')),
            ],
        ),
    ]
