# Generated by Django 3.2.8 on 2021-12-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pre_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.comment', verbose_name='父评论id'),
        ),
    ]
