# Generated by Django 3.2.8 on 2021-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='diary_type',
            field=models.CharField(choices=[('pill', '胶囊日记'), ('primary', '普通日记')], default='胶囊日记', max_length=8),
        ),
        migrations.AddField(
            model_name='article',
            name='expire_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='square_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
