# Generated by Django 3.2.8 on 2021-12-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20211212_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
