# Generated by Django 3.2.8 on 2021-12-12 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_id'),
        ('article', '0004_alter_article_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='article',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.user', verbose_name='作者ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='日记内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='diary_type',
            field=models.CharField(choices=[('pill', '胶囊日记'), ('primary', '普通日记')], default='胶囊日记', max_length=8, verbose_name='日记类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='expire_time',
            field=models.DateTimeField(null=True, verbose_name='解封日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='square_open',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否到期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='日记标题'),
        ),
    ]
